sudo: required
dist: jammy
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-11
      env:
        CXX_COMPILER=g++-11
        C_COMPILER=gcc-11
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-12
      env:
          CXX_COMPILER=g++-12
          C_COMPILER=gcc-12
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-14
      env:
          CXX_COMPILER=clang++-14
          C_COMPILER=clang-14
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-15
      env:
        CXX_COMPILER=clang++-15
        C_COMPILER=clang-15
      
before_install:
# Get build dependencies
- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
- sudo apt-get install -qq cmake build-essential libasound2-dev libxxf86vm-dev
- export CXX=$CXX_COMPILER
- export CC=$C_COMPILER
#- sudo apt-get install -qq gcc-multilib g++-multilib
install:
# Create unix makefiles
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ../
script:
# Build CaesarIA
- make -j4
notifications:
    slack:
        - caesariagame:m3lwdYPWqeCOn0zWs0rjX5KY
    irc:
        - "irc.quakenet.org#caesaria"
    on_failure: always
    on_success: never
